<?php
// includes/ajax-card-details.php
if ( ! defined( 'ABSPATH' ) ) exit; // Prevent direct access

// Register AJAX endpoints for frontend
add_action('wp_ajax_alba_get_card_details', 'alba_board_get_card_details_ajax');
add_action('wp_ajax_nopriv_alba_get_card_details', 'alba_board_get_card_details_ajax');

/**
 * Handle the AJAX request to fetch card details.
 */
function alba_board_get_card_details_ajax() {
    // 1. Verify Nonce for security
    $nonce = isset($_GET['nonce']) ? sanitize_text_field(wp_unslash($_GET['nonce'])) : '';
    if (!wp_verify_nonce($nonce, 'alba_get_card_details')) {
        wp_send_json_error(['message' => esc_html__('Invalid nonce.', 'alba-board')]);
    }

    // 2. Validate Card ID
    $card_id = isset($_GET['card_id']) ? absint($_GET['card_id']) : 0;
    if (!$card_id) {
        wp_send_json_error(['message' => esc_html__('Invalid card id.', 'alba-board')]);
    }

    // 3. Check Object Cache (Redis/Memcached via Transients)
    $cache_key = 'alba_card_live_frontend_' . $card_id;
    $cached_html = get_transient( $cache_key );

    if ( false !== $cached_html ) {
        // Return instantly if found in memory
        wp_send_json_success(['html' => $cached_html, 'cached' => true]);
    }

    // 4. Generate HTML if not in cache
    ob_start();
    alba_output_card_details_frontend_modal($card_id);
    $html = ob_get_clean();

    // 5. Prevent ghost caching of empty responses
    if ( empty( trim( $html ) ) ) {
        wp_send_json_error(['message' => 'Error: Blank response generated by the server.']);
    }

    // 6. Save the rendered HTML in Cache for 12 hours
    set_transient( $cache_key, $html, 12 * HOUR_IN_SECONDS );
    
    // 7. Send the successful response
    wp_send_json_success(['html' => $html, 'cached' => false]);
}

/**
 * Render the HTML payload for the frontend modal.
 * @param int $card_id The ID of the card.
 */
function alba_output_card_details_frontend_modal( $card_id ) {
    $card = get_post($card_id);
    if (!$card || $card->post_type !== 'alba_card') return;

    // Check if the interactions add-on is active
    include_once(ABSPATH . 'wp-admin/includes/plugin.php');
    $addon_active = is_plugin_active('alba-board-frontend-interactions/alba-board-frontend-interactions.php');
    
    ?>
    <div class="alba-modal-inner">
        <h2 class="alba-modal-title"><?php echo esc_html($card->post_title); ?></h2>
        
        <?php
        // Render Assignee
        $author_id = $card->post_author;
        $user = get_user_by('ID', $author_id);
        if ($user): ?>
            <div class="alba-assignee">
                <strong><?php esc_html_e('Assignee:', 'alba-board'); ?></strong>
                <?php echo esc_html($user->display_name); ?>
            </div>
        <?php endif; 
        
        // 👉 DUE DATE FOR THE MODAL FRONTEND
        $due_date = get_post_meta($card_id, 'alba_due_date', true);
        if (!empty($due_date)): 
            // Format full date based on WordPress settings (e.g., "F j, Y")
            $formatted_full_date = date_i18n(get_option('date_format'), strtotime($due_date));
        ?>
            <div class="alba-due-date" style="margin-top: 10px; color: #475569; font-size: 14px;">
                <strong><?php esc_html_e('Due Date:', 'alba-board'); ?></strong> 
                <span class="dashicons dashicons-calendar-alt" style="font-size: 14px; margin-top: 3px;"></span> <?php echo esc_html($formatted_full_date); ?>
            </div>
        <?php endif; ?>

        <div class="alba-description" style="margin-top: 15px;">
            <?php
            // Render Description
            $description = trim($card->post_content);
            echo ($description !== '') ? nl2br(esc_html($description)) : '<span>' . esc_html__('No description.', 'alba-board') . '</span>';
            ?>
        </div>
        
        <?php
        // Render Tags
        $tags = get_the_terms($card_id, 'alba_tag');
        if (!empty($tags) && !is_wp_error($tags)): ?>
            <div class="alba-card-tags">
                <?php foreach ($tags as $tag):
                    $bg = get_term_meta($tag->term_id, 'alba_tag_bg_color', true) ?: 'var(--alba-btn-bg)';
                    $text = get_term_meta($tag->term_id, 'alba_tag_text_color', true) ?: 'var(--alba-text-main)';
                    ?>
                    <span class="alba-card-tag-chip" style="<?php echo 'background:' . esc_attr($bg) . '; color:' . esc_attr($text) . ';'; ?>">
                        <?php echo esc_html($tag->name); ?>
                    </span>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
        
        <div class="comments-title"><strong><?php esc_html_e('Comments:', 'alba-board'); ?></strong></div>
        <div class="alba-card-comments-scrollable" id="alba-comments-list">
            <?php
            // Render Comments
            $comments = get_post_meta($card_id, 'alba_comments', true);
            if (!is_array($comments)) $comments = [];
            
            if (!empty($comments)) {
                foreach ($comments as $i => $c) {
                    ?>
                    <div class="alba-board-comment" data-comment-index="<?php echo esc_attr($i); ?>">
                        <span class="alba-comment-author"><strong><?php echo esc_html($c['author']); ?></strong></span>
                        <span class="alba-comment-date"><?php echo esc_html($c['date']); ?></span>
                        <div class="alba-comment-text"><?php echo esc_html($c['text']); ?></div>
                    </div>
                    <?php
                }
            } else { 
                echo '<div class="alba-no-comments">' . esc_html__('No comments yet.', 'alba-board') . '</div>'; 
            }
            ?>
        </div>
        
        <?php 
        // Render Interactive Features if Add-on is active
        if ($addon_active): ?>
            <div class="alba-add-comment-section">
                <textarea id="alba-new-comment-text" class="alba-form-input-text" data-card-id="<?php echo esc_attr($card_id); ?>" rows="2" placeholder="<?php esc_attr_e('Write a comment...', 'alba-board'); ?>"></textarea>
                <button id="alba-add-comment-btn" class="alba-btn-neumorphic"><?php esc_html_e('Add comment', 'alba-board'); ?></button>
                <div id="alba-comment-feedback"></div>
            </div>
            <div class="alba-modal-delete-section" style="margin-top: 15px; text-align: right;">
                <button id="alba-modal-delete" class="alba-btn-cancel" title="<?php esc_attr_e('Delete', 'alba-board'); ?>"><?php esc_html_e('Delete Card', 'alba-board'); ?></button>
            </div>
        <?php endif; ?>
    </div>
    <?php
}